### ISSUE TITLE
Unable to install some packages on Proton 5.13 created prefix

### ISSUE THREAD

**Issue by mmbossoni** [Winetricks/winetricks#1648]
Some packages like wmp11 tries to install wsh57 that doesn't install properly due to dlls being a symbolic link to Proton wine dlls instead of a regular file.

**Comment by steeznson** [comment]
Hi I'm sorry I missed this bug report and opened another one. I had exactly the same issue as mmbossoni and I have a workaround that allows the packages to be installed.
Steps to reproduce/output:
```
~ $ PATH=~/.steam/steam/steamapps/common/Proton\ 5.13/dist/bin/:$PATH WINEPREFIX=~/.steam/steam/steamapps/compatdata/1018010/pfx sh downloads/winetricks wsh57
Executing mkdir -p /home/steeznson/.steam/steam/steamapps/compatdata/1018010
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: 3eca348b02a12aef2aeae16f3ce41c53a48304b89c2133fe594f636798854fd7 with wine-5.13-634-gd6646652a2f and WINEARCH=win64
Executing w_do_call wsh57
Executing mkdir -p /home/steeznson/.steam/steam/steamapps/compatdata/1018010
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_wsh57 
Executing cabextract -q -d /home/steeznson/.steam/steam/steamapps/compatdata/1018010/pfx/dosdevices/c:/windows/syswow64 /home/steeznson/.cache/winetricks/wsh57/scripten.exe
/home/steeznson/.steam/steam/steamapps/compatdata/1018010/pfx/dosdevices/c:/windows/syswow64/dispex.dll: Permission denied
/home/steeznson/.steam/steam/steamapps/compatdata/1018010/pfx/dosdevices/c:/windows/syswow64/jscript.dll: Permission denied
/home/steeznson/.steam/steam/steamapps/compatdata/1018010/pfx/dosdevices/c:/windows/syswow64/scrobj.dll: Permission denied
/home/steeznson/.steam/steam/steamapps/compatdata/1018010/pfx/dosdevices/c:/windows/syswow64/scrrun.dll: Permission denied
/home/steeznson/.steam/steam/steamapps/compatdata/1018010/pfx/dosdevices/c:/windows/syswow64/vbscript.dll: Permission denied
/home/steeznson/.steam/steam/steamapps/compatdata/1018010/pfx/dosdevices/c:/windows/syswow64/cscript.exe: Permission denied
/home/steeznson/.steam/steam/steamapps/compatdata/1018010/pfx/dosdevices/c:/windows/syswow64/wscript.exe: Permission denied
/home/steeznson/.steam/steam/steamapps/compatdata/1018010/pfx/dosdevices/c:/windows/syswow64/wshom.ocx: Permission denied
------------------------------------------------------
warning: Note: command cabextract -q -d /home/steeznson/.steam/steam/steamapps/compatdata/1018010/pfx/dosdevices/c:/windows/syswow64 /home/steeznson/.cache/winetricks/wsh57/scripten.exe returned status 1. Aborting.
------------------------------------------------------
```
Workaround:
The cabextract actually succeeds the first time so you can just try to install again with that step skipped.
Comment out `w_try_cabextract -d "${W_SYSTEM32_DLLS}" "${W_CACHE}"/wsh57/scripten.exe` in `load_wsh57()` in winetricks script and retry install command.

**Comment by austin987** [comment]
I don't use proton, so someone that does will need to look at this.

**Comment by Nik7413** [comment]
Can you please specify where load_wsh57() is exactly?

**Comment by steeznson** [comment]
@Nik7413 It's a function in the winetricks script
```steeznson@velazquez ~/downloads $ wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
--2020-12-13 17:27:21--  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
Resolving raw.githubusercontent.com... 199.232.52.133
Connecting to raw.githubusercontent.com|199.232.52.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 880242 (860K) [text/plain]
Saving to: winetricks

winetricks                                      100%[=======================================================================================================>] 859.61K  --.-KB/s    in 0.08s   

2020-12-13 17:27:21 (10.2 MB/s) - winetricks saved [880242/880242]

steeznson@velazquez ~/downloads $ grep -nR load_wsh57
winetricks:13275:load_wsh57()

```

**Comment by Nik7413** [comment]
Yup,found it. Thanks

**Comment by Nik7413** [comment]
@steeznson Can you please help me. wmp installed fine but i am also trying to install a package called "quartz". Using you method i commented out some lines in 11670 and 11697 yet its still not working giving me this error:
![Screenshot_20201214_075327](https://user-images.githubusercontent.com/26522894/102033468-8304d500-3de1-11eb-8411-3db592efa01f.png)

**Comment by Nik7413** [comment]
![Screenshot_20201214_080512](https://user-images.githubusercontent.com/26522894/102034084-26a2b500-3de3-11eb-9c49-22f37f318783.png)
These are the lines. I edited them in vim.

**Comment by steeznson** [comment]
@Nik7413 My hypothesis when I originally raised the ticket was that `w_try_cabextract` was returning a non-zero exit status _after it had already completed the extraction_ and then terminating the package installation. Perhaps the way proton prefixes setup permissions cabextract will always yield and error.
Since the quartz error also happens with that function it still appears to be an issue. Also there are two `w_try_cabextract` calls one after the other there so if the first one 'fails' the second one ought to as well.
I was looking originally at wsh57/wmp11 when I first investigated and found my solution for wsh57 through trial and error. I'll take a look at quartz today.

**Comment by steeznson** [comment]
@Nik7413 Ok I managed to install quartz using an extremely convoluted method of running winetricks, hitting an error, copying out the line that raised the error, then re-running winetricks.
`w_try_cabextract` and `w_try cp` both appear to raise a non-zero exit error in the winetricks script due to permissions issues despite the fact that they both succeed.
If I were to start working on a solution to this issue it would likely be a winetricks flag that instructs the `w_try` commands to ignore permissions errors.

**Comment by Nik7413** [comment]
@steeznson So, what should i do on my part to get it working on my end? And also another issue,this time regarding 'devenum'( extremely sorry if it bothers you). This is (i think) the last of the hurdles to get the game running(theoritically)
![Screenshot_20201214_101741](https://user-images.githubusercontent.com/26522894/102085742-0e5f8400-3e3d-11eb-83da-8d8b0c5b3447.png)

**Comment by mmbossoni** [comment]
@Nik7413, my workaround for the time being is find out everything I want to install using winetricks, deleting the prefix and running winetricks before hitting the play button.
That way winetricks runs without any problem.

**Comment by steeznson** [comment]
@Nik7413 I would recommend trying the fix from @mmbossoni since that sounds more clean. As I mentioned I managed to install quartz by:

1. Running winetricks command to try install it
2. When an error appears find the exact point where the `w_try_cabextract` or or `w_try cp` command fails and comment that out in the winetricks script
3. Go back to step 1 (repeat this process until the installation works)

I suspect that approach would work with devenum too. Remember the trick to this approach is that the commands are reporting failures and terminating the installation when they are actually succeeding, so provided you comment out and re-run each step in order you get to the point where the full install has taken place. It's a bad solution but worked for me.

**Comment by wereii** [comment]
I've hit this same error with installing `directplay` verb in proton prefix.

From what it seems this is caused by cabextract "following" symlinks and Proton having the linked files marked as unwritable (perms 444).

**Comment by Seegras** [comment]
winetricks cabextract fails if there are pre-existing files in the prefix that are
- not writable (mode 444 for instance; cabextract itself produces such)
- symlinks
It's a problem with wsh57, gdiplus, quartz, and possibly more.

**Comment by soredake** [comment]
msasn1 affected too.

**Comment by PlaidPhantom** [comment]
FWIW I can confirm this is still an issue particularly with "amstream". My fix so far has been to roll Proton back to 5.0 so I can run winetricks to fix video playback for a number of games.

**Comment by fuzunspm** [comment]
I have the same issue and @mmbossoni 's workaround is working. I was trying to install dotnet472 ole32 gdiplus in a proton 6.19 game prefix

**Comment by patlefort** [comment]
It will fail to do `cp` if the destination is a symlink if the symlink point to a file that you don't have permission to write. If you do have permission, it will overwrite the target of the symlink, which in this case will overwrite something in the proton or wine installation rather than the prefix, which is probably not what you want. Maybe the script should try removing the destination file before copying?

**Comment by truboxl** [comment]
The fix should be at cabextract side: https://github.com/kyz/libmspack/issues/42

**Comment by EstorOG** [comment]
Found an awful workaround for this without editing the winetricks script.
I changed the access permissions of the proton folder to "Can View Modify Content" for the owner, group and others.
So if you want to use proton-ge, have it properly installed and have chosen it for the game under Compatibility but winetricks errors out (when using protontricks) then do what i said previously. It worked for me somehow.

Also sorry im not a developer or anything, just found this shitty workaround by accident. Running Manjaro KDE on my pc and Endeavour OS with KDE on my laptop.

**Comment by Bunny5390** [comment]
> @Nik7413, my workaround for the time being is find out everything I want to install using winetricks, deleting the prefix and running winetricks before hitting the play button. That way winetricks runs without any problem.

An imo easier solution is to let Steam and Proton create the wineprefix, then simply delete the problematic symbolic links in it.
Winetricks (via Protontricks as in the issues referencing this) then runs just fine. I even got the the game I wanted (Magellania) running \o/

**Comment by tralph3** [comment]
This is also an issue with vcrun2017

**Comment by austin987** [comment]
This really should be fixed on the cabextract side. There are currently ~200 calls to cabextract that would need to be investigated to 'fix' this (hackily) on the winetricks side.

**Comment by Coolguy3289** [comment]
> This really should be fixed on the cabextract side. There are currently ~200 calls to cabextract that would need to be investigated to 'fix' this (hackily) on the winetricks side.

With this being said, is there any pressure that Winetricks can put on the cabextract team to get this resolved? There is a PR that was started to fix this issue (https://github.com/kyz/libmspack/pull/43) and it's not been merged yet. The PR is just shy of 2 years old, and the issue is still plaguing winetricks installs today.

**Comment by austin987** [comment]
I don't think winetricks has any leverage here. In my blunt opinion, if anything, Proton/Valve/Steam should be the one taking the initiative here. Given that this only affects their fork, and that they're funding FOSS work, in my view, it makes sense for them to (have someone) send a PR adding symlink support.

I've (previously) upvoted comments on the related libmspack issue, but as I said, it's a separate project and I don't have any influence over it. Affected users are welcome to subscribe themselves (or, ideally, will send a PR themselves ;) ).

**Comment by austin987** [comment]
Cabextract has released a new version, 1.10 that has support for keeping symlinks. If you're using Proton 5.13 and can get the newer cabextract, please try https://github.com/Winetricks/winetricks/pull/2025 and see if that fixes the issue.

**Comment by thelabcat** [comment]
I've installed the latest cabextract, but the Flatpak protontricks is not using it. Will switch to system package protontricks if I can, but is there a workaround?

**Comment by Lemon-522** [comment]
I'm having issues using commands. 
I'm using konsole on my steamdeck to try to run
$ protontricks -c "wine uninstaller" 244210
to try to get a program running for assetto corsa and when I hit enter it says 
bash: protontricks: command not found
I tried running
$ protontricks --help
as that is one of the listed command and it still returns with 
bash: protontricks: command not found
I have protontricks installed through the discover store and I don't see anything saying I should install it another way but clearly something is wrong and I have not the foggiest idea what it could be.
any help would be greatly appreciated.
