### ISSUE TITLE
Winetricks won't start on macOS

### ISSUE THREAD

**Issue by AndnixSH** [Winetricks/winetricks#2250]
Winetricks won't start anymore after upgrading Wine devel to 9.13 in my Mac mini running Sonoma 14.5. It throws this "warning" `warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message ""`. I deleted my prefix and re-create it by starting Winetricks again. WineHQ popups up that it creates a prefix then it throws the same warning again

```
Executing cd .
warning: taskset/cpuset not available on your platform!
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
warning: You appear to be using Wine's new wow64 mode. Note that this is EXPERIMENTAL and not yet fully supported. If reporting an issue, be sure to mention this.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: .
..
.DS_Store
Program Files
Program Files (x86)
ProgramData
users
windows

Registry info:
/Users/xxx/.wine/system.reg:#arch=win64
/Users/xxx/.wine/user.reg:#arch=win64
/Users/xxx/.wine/userdef.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
warning: wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
```

**Comment by AndnixSH** [comment]
> Remove the wineprefix then firstly run
> 
> > wine wineboot -
> 
> Then try installing your desired winetricks verb.

Still getting same warning. I just run winetricks using `./winetricks`

**Comment by AndnixSH** [comment]
The issue is fixed

**Comment by austin987** [comment]
> The issue is fixed

What was the fix?

**Comment by AndnixSH** [comment]
> > The issue is fixed
> 
> What was the fix?

I guess by updating winetricks to latest version again

**Comment by different55** [comment]
Still broken for me with the same error on 20250102. Winetricks is still trying to use this option on macOS, and ncruces/zenity still hasn't added support for --hide-column, and it seems that given its current status, it probably won't be happening.
