### ISSUE TITLE
W2KSP4_EN.EXE no longer available

### ISSUE THREAD

**Issue by nifgraup** [Winetricks/winetricks#600]
```
$ winetricks atmlib
------------------------------------------------------
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing w_do_call atmlib
Executing load_atmlib
Downloading http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE to /home/bjorgvin/.cache/winetricks/win2ksp4
--2016-02-02 19:15:54--  http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE
Resolving download.microsoft.com (download.microsoft.com)... 72.247.86.229, 2001:5002:203:19f::e59, 2001:5002:203:186::e59
Connecting to download.microsoft.com (download.microsoft.com)|72.247.86.229|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-02-02 19:15:55 ERROR 404: Not Found.

------------------------------------------------------
Downloading http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE failed
------------------------------------------------------
```

**Comment by qwertychouskie** [comment]
It is available in the internet archive:
http://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE

**Comment by austin987** [comment]
Fixed by a5e32a8

**Comment by dangowrt** [comment]
The download from archive.org keeps failing after about 7megs. Maybe add ftp://ftp.fu-berlin.de/pc/security/ms-patches/win2000/Service_Packs/usa/W2KSP4_EN.EXE to the list of download mirrors?

**Comment by austin987** [comment]
Please file new bugs for new issues, rather than reusing closed bugs.

That said, I can't reproduce. I've never seen this download fail, and I've been running 'make test' a lot the past few weeks.

Also keep in mind that multiple download mirrors aren't supported for a single download. The original URL is tried, then we fall back to archive.org. Are you sure it's not your ISP? You can use --torify if you're behind a censored one.

**Comment by rbreaves** [comment]
It's an issue for me as well, and I am on suddenlink atm, but I can test it later on a few other ISPs for a more thorough response to this later. I am unfamiliar with the torify flag, but I ran it with that and it's all the same (so unless I need to install tor itself, --torify does nothing for me). I am running Ubuntu 16.04 LTS (in case that matters to anyone).

**Comment by austin987** [comment]
Again, closed issue, don't use this bug, make your own.

You'll need torify installed for --torify to work (winetricks should warn you if it's not installed).

Of course, you'll need a recent winetricks for that, so make sure you're not using Ubuntu's version, which is ridiculously old and broken.

**Comment by giocomai** [comment]
Same issue here, using latest winetricks from github. The link above does not currently work. Not sure it would make sense to open a new issue, as this has not been solved, yet marked as closed. As highlighted above, however, W2KSP4_EN.EXE is available on a number of other mirrors
[http://www.filewatcher.com/m/W2KSP4_EN.EXE.135477136-0.html](http://www.filewatcher.com/m/W2KSP4_EN.EXE.135477136-0.html)

**Comment by austin987** [comment]
Someone with this issue, please run with:
winetricks -q -v atmlib &> atmlib.txt
then
winetricks -q --torify -v atmlib &> atmlib_torify.txt

(or whatever verb you were having problems with), and either paste the full logs in two comments, or email them to me.

I suspect these are old versions of winetricks, as it should be falling back to archive.org.

For future reference, when reporting bugs (here, or anywhere), saying 'latest version', isn't helpful, because it doesn't tell us any version at all (you may think you have the latest, you may not, and in any case, 6 months later, no one knows what version you have). For winetricks and most programs, you can use --version to get that info.

**Comment by austin987** [comment]
Note that I released 20160425 today, so make sure you're running that before getting those logs.

**Comment by giocomai** [comment]
Thanks for the suggestion about --version, of course you're absolutely right. 

To clarify. Winetricks did fall back on archive.org, but archive.org wouldn't respond, either through wget or via the browser (from the browser, it would say to try again). I waited half an hour, tried again multiple times, and still nothing. 
To be absolutely clear, the link suggested above in this thread - http://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE - wouldn't start a download. 

As a workaround, I downloaded the file from one of the other mirrors (http://www.filewatcher.com/m/W2KSP4_EN.EXE.135477136-0.html) and copied the .exe file into /home/USER/.cache/winetricks/win2ksp4, then run again the script and all went smoothly. 

Tried again now (10 hours later) and all works fine, i.e. the link above on archive.org works just fine from both wget and browser.

In brief, this is an archive.org issue. Perhaps adding a second fallback option may be of help.

**Comment by Diogovmm** [comment]
when I try to execute the file it says service "pack 4 setup error: Setup cannot update your windows files because the language installed on your system is different from the update language"
What should I do?

**Comment by austin987** [comment]
Trying to run that exe has nothing at all to do with winetricks. Winetricks only uses it for extracting files from.

Friendly reminder, this is a closed issue.

**Comment by Diogovmm** [comment]
I know it is closed and sorry if I should not post this here.
I posted  because it is the only post I found with the same problem with me and solved it. I have posted on 2 other places and no one helps me I don't know what to do. I started using Linux for about 6-7 days now, trying to get this to work since the beginning...
Can you please help me?

**Comment by austin987** [comment]
I'm not clear at all what you're trying to do

**Comment by Diogovmm** [comment]
I'm trying to get playonlinux and wine to work with blizzard games- hearthstone and heroes of the storm (Hots). when I try to run Hots I get this:
[07/29/16 17:43:37] - Running wine-1.9.10 wineboot (Working directory : /usr/share/playonlinux/python)
err:module:import_dll Library dbghelp.dll (which is needed by L"C:\\windows\\system32\\mscoree.dll") not found
fixme:dwmapi:DwmIsCompositionEnabled 0x6d2ed8b8
fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x6a0a6836, context 0x82dea8, init_notify 0, handle 0x113e7d4): stub
wine: configuration in '/home/xut/.PlayOnLinux/wineprefix/heroes_of_the_storm' has been updated.
[07/29/16 17:44:03] - Running wine-1.9.10 wineboot (Working directory : /usr/share/playonlinux/python)
[07/29/16 17:44:21] - Running wine-1.9.10 Battle.net Launcher.exe (Working directory : /home/xut/.PlayOnLinux/wineprefix/heroes_of_the_storm/drive_c/Program Files/Battle.net)
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:wininet:InternetSetOptionW Option 77 STUB
err:wininet:open_http_connection create_netconn failed: 12029
fixme:ver:GetCurrentPackageId (0x456ea08 (nil)): stub
fixme:wininet:InternetSetOptionW Option 77 STUB
err:wininet:open_http_connection create_netconn failed: 12029
fixme:wininet:InternetSetOptionW Option 77 STUB
err:wininet:open_http_connection create_netconn failed: 12029
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:wininet:InternetSetOptionW Option 77 STUB
err:wininet:open_http_connection create_netconn failed: 12029
fixme:ver:GetCurrentPackageId (0x49bea08 (nil)): stub
fixme:wininet:InternetSetOptionW Option 77 STUB
err:wininet:open_http_connection create_netconn failed: 12029
fixme:wininet:InternetSetOptionW Option 77 STUB
err:wininet:open_http_connection create_netconn failed: 12029
fixme:win:EnumDisplayDevicesW ((null),0,0x33f578,0x00000000), stub!
fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
fixme:wbemprox:client_security_SetBlanket 0x7dbffba8, 0x171f88, 10, 0, (null), 3, 3, (nil), 0x00000000
fixme:wbemprox:client_security_Release 0x7dbffba8
fixme:wininet:InternetSetOptionW Option 77 STUB
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported
fixme:wbemprox:enum_class_object_Next timeout not supported
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:ver:GetCurrentPackageId (0x456ea08 (nil)): stub
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
wine: Call from 0x7b43fb52 to unimplemented function api-ms-win-crt-locale-l1-1-0.dll._lock_locales, aborting
err:module:attach_process_dlls "MSVCP140.dll" failed to initialize, aborting
err:module:LdrInitializeThunk Main exe initialization for L"C:\\Program Files\\Battle.net\\Battle.net.7730\\Battle.net.exe" failed, status 80000100
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
<html><head><title>Object moved</title></head><body>

<h2>Object moved to <a href="http://www.blizzard.com/404">here</a>.</h2>

</body></html>

<html><head><title>Object moved</title></head><body>

<h2>Object moved to <a href="http://www.blizzard.com/404">here</a>.</h2>

</body></html>

<html><head><title>Object moved</title></head><body>

<h2>Object moved to <a href="http://www.blizzard.com/404">here</a>.</h2>

</body></html>

fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
[07/29/16 17:49:06] - ----- Starting function POL_Install_wininet -----
[07/29/16 18:58:50] - Running wine-1.9.10 Battle.net Launcher.exe (Working directory : /home/xut/.PlayOnLinux/wineprefix/heroes_of_the_storm/drive_c/Program Files/Battle.net)
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:wininet:InternetSetOptionW Option 77 STUB
err:wininet:open_http_connection create_netconn failed: 12029
fixme:ver:GetCurrentPackageId (0x456ea08 (nil)): stub
fixme:wininet:InternetSetOptionW Option 77 STUB
err:wininet:open_http_connection create_netconn failed: 12029
fixme:wininet:InternetSetOptionW Option 77 STUB
err:wininet:open_http_connection create_netconn failed: 12029
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:wininet:InternetSetOptionW Option 77 STUB
err:wininet:open_http_connection create_netconn failed: 12029
fixme:ver:GetCurrentPackageId (0x49bea08 (nil)): stub
fixme:wininet:InternetSetOptionW Option 77 STUB
err:wininet:open_http_connection create_netconn failed: 12029
fixme:wininet:InternetSetOptionW Option 77 STUB
err:wininet:open_http_connection create_netconn failed: 12029
fixme:win:EnumDisplayDevicesW ((null),0,0x33f578,0x00000000), stub!
fixme:wbemprox:wbem_locator_ConnectServer unsupported flags
fixme:wbemprox:client_security_SetBlanket 0x7dbffba8, 0x172008, 10, 0, (null), 3, 3, (nil), 0x00000000
fixme:wbemprox:client_security_Release 0x7dbffba8
fixme:wininet:InternetSetOptionW Option 77 STUB
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported
fixme:wbemprox:enum_class_object_Next timeout not supported
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:ver:GetCurrentPackageId (0x456ea08 (nil)): stub
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
fixme:module:load_library unsupported flag(s) used (flags: 0x00000800)
wine: Call from 0x7b43fb52 to unimplemented function api-ms-win-crt-locale-l1-1-0.dll._lock_locales, aborting
err:module:attach_process_dlls "MSVCP140.dll" failed to initialize, aborting
err:module:LdrInitializeThunk Main exe initialization for L"C:\\Program Files\\Battle.net\\Battle.net.7730\\Battle.net.exe" failed, status 80000100
<html><head><title>Object moved</title></head><body>

<h2>Object moved to <a href="http://www.blizzard.com/404">here</a>.</h2>

</body></html>

<html><head><title>Object moved</title></head><body>

<h2>Object moved to <a href="http://www.blizzard.com/404">here</a>.</h2>

</body></html>

<html><head><title>Object moved</title></head><body>

<h2>Object moved to <a href="http://www.blizzard.com/404">here</a>.</h2>

</body></html>

fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform


So I think it is because of wininet and winhttp. Now when I try to install them on POL it says "Error ! Files mismatch" "Error in POL_Download_Resource
MD5 sum mismatch ! (1 attempt)".

Following this post I though I should download W2KSP4.exe mannually and execute at home/USER/.cache/winetricks/win2ksp4 ; this because I used to get an error in wine when I tried to install wininet and winhttp (instead of at POL). I have installed and reistalled many times now both wine and POL. I have POL version 4.2.10; wine 1.8; Ubunto 16.04.1 LTS Xenial

**Comment by Diogovmm** [comment]
> Fixed by a5e32a8

I copied the script mentioned there to my desktop and tried to run it but can't, even with sudo ./name
Is it supposed to fix the issue? if so, how should I run it?

**Comment by austin987** [comment]
On Jul 29, 2016 10:51 PM, "Diogovmm" <notifications@github.com> wrote:
>>
>> Fixed by a5e32a8
>
> I copied the script mentioned there to my desktop and tried to run it but
can't, even with sudo ./name
> Is it supposed to fix the issue? if so, how should I run it?

See https://bugs.winehq.org/show_bug.cgi?id=39663#c5

PlayOnLinux's forum may be able to provide more help. A couple more notes:
* don't run winetricks, or wine, as root/sudo
* windows service packs aren't meant to be used under wine
* ./winetricks should work, but you probably need to chmod +x if you
downloaded from the Internet

It sounds like there is a legit big in that winetricks should set more
overrides for vcrun2015, but that needs its own bug if anyone wants it
fixed.

**Comment by samrocketman** [comment]
I have checked out the latest master of winetricks and installed it.  d1c3d3f53491a4534368ba06a3f5ecf005a32936

I still get this exact error.  Why was this closed as resolved?

**Comment by makefile** [comment]
find a good download url:[http://x3270.bgp.nu/download/specials/W2KSP4_EN.EXE](http://x3270.bgp.nu/download/specials/W2KSP4_EN.EXE)

**Comment by MetaiR** [comment]
has a problem on wine 2.4
![image](https://cloud.githubusercontent.com/assets/7807264/24592094/a257a940-1825-11e7-9065-eac60b187c45.png)

**Comment by austin987** [comment]
@MetaiR the wine version is irrelevant, your winetricks is very outdated.

**Comment by MetaiR** [comment]
@austin987 
how should I update it?

**Comment by austin987** [comment]
https://wiki.winehq.org/Winetricks#Installing_winetricks

You could use --self-update, but your version may be too old for that.

If you got winetricks from your distribution, ask them to update it.

**Comment by ritviksharma24** [comment]
Hi, I've noticed the difficulty in downloading W2KSP4_EN.EXE , so I downloaded one painfully after 4 hours of troubles, and uploaded it to Google drive, download from here:

https://drive.google.com/open?id=0B-q4OkYnpl0XMW5FMjRPd2ZFVlE

**Comment by Nic30** [comment]
same for me

**Comment by danger89** [comment]
This is again an issue...

**Comment by yinrong** [comment]
who has W2KSP4_EN.EXE now ? all link above fails now.

**Comment by rbreaves** [comment]
Looks like the archive link above is working once again.
http://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE

**Comment by Balthazar22** [comment]
> who has W2KSP4_EN.EXE now ? all link above fails now.

It's available from http://x3270.bgp.nu/download/specials/W2KSP4_EN.EXE - this is the source used by the Ubuntu Snap acrordrdc

**Comment by tribhuwan-kumar** [comment]
> > who has W2KSP4_EN.EXE now ? all link above fails now.
> 
> It's available from http://x3270.bgp.nu/download/specials/W2KSP4_EN.EXE - this is the source used by the Ubuntu Snap acrordrdc

its painfully slow :(
